# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20240429-115231-direct-spear

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline: 
  - name: "SpacyNLP"
    model: "en_core_web_md"
    case_sensitive: False
  - name: "SpacyTokenizer"
    intent_tokenization_flag: False
    intent_split_symbol: "_"
    token_pattern: None
  - name: "SpacyFeaturizer"   
    pooling: "mean"
  - name: LanguageModelFeaturizer
    model_name: "bert"
    model_weights: "rasa/LaBSE"
    cache_dir: null
  - name: LexicalSyntacticFeaturizer
    case_sensitive: False
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    entity_recognition: False
    constrain_similarities: true
    ambiguity_threshold: 0.2
  - name: FallbackClassifier
    threshold: 0.2
    



# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
- name: MemoizationPolicy
  max_history: 4
- name: RulePolicy
  core_fallback_threshold: 0.2
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: True
- name: UnexpecTEDIntentPolicy
  epochs: 50
- name: TEDPolicy
  max_history: 8
  epochs: 150
  constrain_similarities: true
